- name: Install zsh via apt.
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Remove Darwin PATH lookup from .zshrc.
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.blockinfile:
    path: "~/.config/zsh/.zshrc"
    marker: "# Homebrew lookup for Darwin - ANSIBLE MANAGED BLOCK"
    block: ""
