- name: Install and configure NVM.
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Download NVM installation script.
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
        dest: /tmp
        mode: "0755"

    - name: Ensure that NVM directory exists for installation.
      ansible.builtin.file:
        path: ~/bin/nvm
        state: directory

    - name: Install NVM (without modifying .zshrc).
      ansible.builtin.shell:
        cmd: PROFILE=/dev/null NVM_DIR=~/bin/nvm /tmp/install.sh
        executable: /usr/bin/zsh
      changed_when: true

    - name: Modify .zshrc to include NVM_DIR and nvm.sh.
      ansible.builtin.blockinfile:
        path: ~/.config/zsh/.zshrc
        marker_begin: NVM binary lookup -
        insertafter: "# END ANSIBLE MANAGED BLOCK"
        block: |
          export NVM_DIR="$HOME"/bin/nvm
          [ -s "$NVM_DIR"/nvm.sh ] && source "$NVM_DIR"/nvm.sh

        prepend_newline: true

- name: Remove the temporary files.
  ansible.builtin.file:
    path: /tmp/install.sh
    state: absent

- name: Install Node and NPM.
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.shell:
    cmd: source ~/.config/zsh/.zshrc && nvm install {{ node_version }}
    executable: /usr/bin/zsh
  changed_when: true
