#!/usr/bin/env bash

set -e 

COMMIT_MSG_FILE=$1

IFS="/" read -r -a GIT_BRANCH < <(git rev-parse --abbrev-ref HEAD)

# ${GIT_BRANCH[-1]} for bash 4.0+.
COMMIT_TITLE=${GIT_BRANCH[${#GIT_BRANCH[@]} - 1]}

sed -i '' -e "1 s/^.*$/\[$COMMIT_TITLE\]/" "$COMMIT_MSG_FILE"





