# Installation
neovim:
  linux:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
  darwin:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
# Languages
# Go
go_version: 1.22.4
go:
  linux:
    arm64: https://go.dev/dl/go{{ go_version }}.linux-arm64.tar.gz
    amd64: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
# .NET
dotnet_sdk_version: 8.0
dotnet_pkg_name: dotnet-sdk-{{ dotnet_sdk_version }}
# Javascript
nvm_version: 0.39.7
node_version: 20
# Tools
tools:
  go_install:
    - "github.com/google/yamlfmt/cmd/yamlfmt@latest"
    - "github.com/go-delve/delve/cmd/dlv@latest"
  npm_install:
    - name: prettier
    - name: eslint_d
    - name: typescript
  prebuilt:
    - name: jq
      url:
        arm64: 'https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-arm64'
        amd64: 'https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64'
      extract: "false"
    - name: shellcheck
      url:
        arm64: 'https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.aarch64.tar.xz'
        amd64: 'https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz'
      extract: "true"
    - name: golangci-lint
      url:
        arm64: 'https://github.com/golangci/golangci-lint/releases/download/v1.59.1/golangci-lint-1.59.1-darwin-arm64.tar.gz'
        amd64: 'https://github.com/golangci/golangci-lint/releases/download/v1.59.1/golangci-lint-1.59.1-linux-amd64.tar.gz'
      extract: "true"
