- name: Install Docker via Docker Desktop.
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Download Docker.dmg.
      ansible.builtin.get_url:
        url: "{{ docker_packages.Darwin.url }}"
        dest: /tmp/{{ docker_packages.Darwin.name }}.dmg

    - name: Mount the .dmg to start installation.
      ansible.builtin.command:
        cmd: hdiutil attach /tmp/{{ docker_packages.Darwin.name }}.dmg
      register: mount_out
      changed_when: not mount_out.stderr is defined

    - name: Run the installation script.
      ansible.builtin.command:
        cmd: /Volumes/Docker/Docker.app/Contents/MacOS/install --user={{ lookup('env', 'USER') }}
      register: install_out
      changed_when: not install_out.stderr is defined

- name: Detach the .dmg after installation.
  ansible.builtin.command:
    cmd: hdiutil detach /tmp/{{ docker_packages.Darwin.name }}.dmg
  register: detach_out
  changed_when: not detach_out.stderr is defined

- name: Remove the temporary files.
  ansible.builtin.file:
    path: /tmp/{{ docker_packages.Darwin.name }}.dmg
    state: absent

