- name: Ensure that sublists are created for both archive and package installations.
  ansible.builtin.set_fact:
    archive_installation: "{{ hashicorp_tools.Darwin | selectattr('type', 'equalto', 'archive') }}"
    package_installation: "{{ hashicorp_tools.Darwin | selectattr('type', 'equalto', 'package') }}"

- name: Download binaries from Hashicorp.
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /tmp/{{ item.name }}{{ '.zip' if item.type == 'archive' else '.dmg' }}
  with_items: "{{ hashicorp_tools.Darwin }}"

- name: "[Archive] Install Hashicorp tools under $HOME/bin."
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: "Ensure that temporary directory exists to hold the unarchived files."
      ansible.builtin.file:
        path: /tmp/{{ item.name }}
        state: directory
      with_items: "{{ archive_installation }}"

    - name: "Unarchive the binary."
      ansible.builtin.unarchive:
        src: /tmp/{{ item.name }}.zip
        dest: /tmp/{{ item.name }}
      with_items: "{{ archive_installation }}"

    - name: "Move the binary under $HOME/bin."
      ansible.builtin.command:
        cmd: mv /tmp/{{ item.name }}/{{ item.name }} ~/bin
        removes: /tmp/{{ item.name }}/{{ item.name }}
        creates: ~/bin/{{ item.name }}
      with_items: "{{ archive_installation }}"

    - name: "Remove temporary directories after installation."
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/{{ item.name }}.zip
        - /tmp/{{ item.name }}

- name: "[Package] Install Hashicorp tools under $HOME/bin."
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Mount the .dmg images.
      ansible.builtin.command:
        cmd: hdituil attach /tmp/{{ item.name }}.dmg

    - name: Install tools by running the .pkg file.
      ansible.builtin.command:
        cmd: installer -pkg {{ item.pkg }} -target /
      with_items: "{{ package_installation }}"

    - name: Move the source code under $HOME/lib.
      ansible.builtin.command:
        cmd: mv {{ item.lib }} ~/lib
        creates: ~/lib/{{ item.lib }}
        removes: "{{ item.lib }}"
      with_items: "{{ package_installation }}"

    - name: Remove the global symlink under /usr/local/bin.
      ansible.builtin.file:
        path: "{{ item.link }}"
        state: absent
      with_items: "{{ package_installation }}"

    - name: Create a new local symlink under $HOME/bin.
      ansible.builtin.file:
        src: ~/lib/{{ item.name }}/bin/{{ item.name }}
        dest: ~/bin/{{ item.name }}
        state: link

    - name: Unmount the image after installation.
      ansible.builtin.command:
        cmd: hdiutil detach /tmp/{{ item.name }}.dmg
      with_items: "{{ package_installation }}"

    - name: Remove the image after installation.
      ansible.builtin.file:
        path: /tmp/{{ item.name }}.dmg
        state: absent
      with_items: "{{ package_installation }}"
