- name: Install Hashicorp tools under $HOME.
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Download binaries from Hashicorp.
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: /tmp/{{ item.name }}.zip
      with_items: "{{ hashicorp_tools.Linux }}"

    - name: Ensure that temporary directories exist for unarchived files.
      ansible.builtin.file:
        path: /tmp/{{ item.name }}
        state: directory
      with_items: "{{ hashicorp_tools.Linux }}"

    - name: Unarchive the downloads.
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/{{ item.name }}.zip
        dest: /tmp/{{ item.name }}
      with_items: "{{ hashicorp_tools.Linux }}"

    - name: Move the unarchived binaries under $HOME/bin/prebuilt.
      ansible.builtin.command:
        cmd: mv /tmp/{{ item.name }}/{{ item.name }} ~/bin/prebuilt
        removes: /tmp/{{ item.name }}/{{ item.name }}
        creates: ~/bin/{{ item.name }}
      with_items: "{{ hashicorp_tools.Linux }}"

    - name: Remove the temporary directories.
      ansible.builtin.file:
        path: /tmp/{{ item.name }}
        state: absent
      with_items: "{{ hashicorp_tools.Linux }}"

    - name: Remove the downloads.
      ansible.builtin.file:
        path: /tmp/{{ item.name }}.zip
        state: absent
      with_items: "{{ hashicorp_tools.Linux }}"
