- name: Download AWS CLI pkg.
  ansible.builtin.get_url:
    url: "{{ aws_archive_url[arch] }}"
    dest: /tmp/awscli.pkg

- name: Install AWS CLI via Darwin installer.
  ansible.builtin.command:
    cmd: installer -pkg /tmp/awscli.pkg -target /
  changed_when: true

- name: Ensure that installation is done under $HOME.
  block:
    - name: Remove the global AWS CLI symlink.
      ansible.builtin.file:
        path: /usr/local/bin/aws
        state: absent

    - name: Ensure that $HOME/lib exists for local installations.
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.file:
        path: ~/lib
        state: directory
        mode: "0755"

    - name: Move the CLI installation under $HOME/lib.
      ansible.builtin.command:
        cmd: mv /usr/local/aws-cli /home/{{ lookup('env', 'USER') }}/lib
        removes: /usr/local/aws-cli
        creates: /home/{{ lookup('env', 'USER') }}/lib/aws-cli

    - name: Ensure that necessary symlinks for AWS CLI are created under $HOME/bin.
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {src: ~/lib/aws-cli/v2/current/bin/aws, dest: ~/bin/aws}
        - {src: ~/lib/aws-cli/v2/current/bin/aws-completer, dest: ~/bin/aws-completer,}

- name: Remove the temporary files.
  ansible.builtin.file:
    path: /tmp/awscli.pkg
    state: absent
