- name: "[OS Specific] Install Podman on Darwin."
  ansible.builtin.include_tasks: ./setup-Darwin.yml
  when: ansible_os_family == "Darwin"

- name: "[OS Specific] Install Podman on Linux."
  ansible.builtin.include_tasks: ./setup-Linux.yml
  when: ansible_os_family != "Darwin"
