- name: "Install .NET."
  block:
    - name: "Download dotnet-tools."
      ansible.builtin.get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: /tmp
        owner: "{{ dotfiles_user }}"
        group: "{{ dotfiles_user_group }}"
        mode: "0755"

    - name: "Ensure that provided .NET installation directories exist."
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ dotfiles_user }}"
        group: "{{ dotfiles_user_group }}"
        mode: "0755"
      with_items:
        - "{{ dotnet_lang_path }}"

    - name: "Install .NET via dotnet-tools."
      become_user: "{{ dotfiles_user }}"
      ansible.builtin.shell:
        cmd: /tmp/dotnet-install.sh --channel {{ dotnet_sdk_version }} --install-dir {{ dotnet_lang_path }}
      register: dotnet_install_out
      changed_when: not dotnet_install_out.stderr is defined

- name: "Remove the temporary files."
  ansible.builtin.file:
    path: /tmp/dotnet-install.sh
    state: absent
