- name: "Install Rust."
  become: true
  block:
    - name: "Download and run Rustup."
      become_user: "{{ dotfiles_user }}"
      ansible.builtin.shell:
        cmd: source {{ xdg_config_home }}/{{ dotfiles_shell }}/.{{ dotfiles_shell }}rc && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        executable: "{{ dotfiles_shell_executable_path }}"

    - name: "Ensure that Cargo permissions are set correctly."
      ansible.builtin.file:
        path: "{{ xdg_bin_home }}/cargo"
        state: directory
        recurse: true
        owner: "{{ dotfiles_user }}"
        group: "{{ dotfiles_user_group }}"
