- name: "Install Rust."
  become_user: "{{ dotfiles_user }}"
  block:
    - name: "Download and run Rustup."
      ansible.builtin.shell:
        cmd: source {{ xdg_config_home }}/{{ dotfiles_shell }}/.{{ dotfiles_shell }}rc && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        executable: "{{ dotfiles_shell_executable_path }}"
