- name: Ensure that the configuration files are under $XDG_CONFIG_HOME.
  become_user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Ensure that $XDG_CONFIG_HOME/git exists.
      ansible.builtin.file:
        path: ~/.config/git
        state: directory

    - name: Ensure that the symlinks are created under $XDG_CONFIG_HOME/git.
      ansible.builtin.file:
        src: "{{ role_path }}/files/{{ item }}"
        path: ~/.config/git/{{ item }}
        state: link
        force: true
      with_items:
        - hooks
        - config

- name: Ensure that an ed25519 SSH key/pair is generated for remote Git access.
  become_user: "{{ lookup('env', 'USER') }}"
  community.crypto.openssh_keypair:
    path: ~/.ssh/git
    type: ed25519
    force: false
