- name: Install git-delta as a custom pager for Git.
  block:
    - name: Download git-delta binary.
      ansible.builtin.get_url:
        url: "{{ delta_url[arch][ansible_os_family] }}"
        dest: /tmp/delta.zip

    - name: Disable 'Unknown Developer' warning.
      community.general.xattr:
        path: "/tmp/delta.zip"
        state: absent

    - name: Ensure that temporary directory exists for installation.
      ansible.builtin.file:
        path: /tmp/delta
        state: directory

    - name: Extract git-delta download.
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/delta.zip
        dest: /tmp/delta

    - name: Ensure that git-delta binary is moved under $HOME/bin/prebuilt.
      ansible.builtin.command:
        cmd: "mv /tmp/delta/usr/bin/delta /home/{{ lookup('env', 'USER') }}/bin/prebuilt"
        removes: /tmp/delta/usr/bin/delta
        creates: /home/{{ lookup('env', 'USER') }}/bin/prebuilt/delta

    - name: Remove temporary files.
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/delta
        - /tmp/delta.zip
