- name: Install git-delta as a custom pager for Git.
  block:
    - name: Download git-delta binary.
      ansible.builtin.get_url:
        url: "{{ delta_url[arch][ansible_os_family] }}"
        dest: /tmp/delta.tar.gz

    - name: Create a temporary folder to store the unarchived files.
      ansible.builtin.file:
        path: /tmp/delta-binary
        state: directory

    - name: Extract git-delta download.
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/delta.tar.gz
        dest: /tmp/delta-binary
        extra_opts: [--strip-components=1]

    - name: Ensure that git-delta binary is moved under $HOME/bin/prebuilt.
      ansible.builtin.command:
        cmd: "mv /tmp/delta-binary/delta /home/{{ lookup('env', 'USER') }}/bin/prebuilt"
        removes: /tmp/delta-binary/delta
        creates: /home/{{ lookup('env', 'USER') }}/bin/prebuilt/delta

    - name: Remove temporary files.
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/delta-binary
        - /tmp/delta.tar.gz
