# Installation.
neovim:
  linux:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz

neovim_unarchive_path: "{{ lib_path }}"

gcc_packages:
  Archlinux:
    - "gcc"
    - "gcc-go"
    - "gcc-rust"
    - "cmake"

# Languages.
# Go.
go_version: 1.22.4
go:
  linux:
    amd64: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz

# .NET.
dotnet_sdk_version: 9.0

# Javascript.
nvm_version: 0.39.7
node_version: 20

# Programs.
programs:
  go_install:
    - "github.com/google/yamlfmt/cmd/yamlfmt@latest"
    - "github.com/go-delve/delve/cmd/dlv@latest"
  npm_install:
    - name: eslint_d
    - name: typescript
  prebuilt:
    - name: jq
      url:
        amd64: 'https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64'
      extract: "false"
    - name: shellcheck
      url:
        amd64: 'https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz'
      extract: "true"
      strip: "true"
    - name: golangci-lint
      url:
        amd64: 'https://github.com/golangci/golangci-lint/releases/download/v1.59.1/golangci-lint-1.59.1-linux-amd64.tar.gz'
      extract: "true"
      strip: "true"
    - name: fzf
      url:
        amd64: 'https://github.com/junegunn/fzf/releases/download/v0.60.2/fzf-0.60.2-linux_amd64.tar.gz'
      extract: "true"
      strip: "false"
    - name: rg
      url:
        amd64: 'https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz'
      extract: "true"
      strip: "true"
    - name: fd
      url:
        amd64: 'https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-gnu.tar.gz'
      extract: "true"
      strip: "true"
