# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ANSIBLE_VERSION = "2.16.6"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/fedora-39-arm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  # A basic provisioning for 1 VM.
  config.vm.provider :vmware_desktop do |vmware|
    vmware.memory = 512
    vmware.cpus = 1
    vmware.vmx["ethernet0.pcislotnumber"] = "160"
  end

  config.vm.define "app" do |app|
    app.vm.network :private_network, ip: "192.168.56.5"

    config.vm.provision "repo-setup", type: "ansible" do |ansible|
      ansible.version = ANSIBLE_VERSION
      ansible.playbook = "../provision.yml"
    end

    config.vm.provision "test", run: "never", type: "ansible" do |ansible|
      ansible.version = ANSIBLE_VERSION
      ansible.playbook = "../playbook.yml"
    end
  end
end

