# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202404.26.0"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  # A basic provisioning for 1 VM.
  config.vm.provider :vmware_desktop do |vmware|
    vmware.memory = 512
    vmware.cpus = 1
  end

  config.vm.define "app" do |app|
    app.vm.network :private_network, ip: "192.168.56.5"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbook.yml"
    end
  end
end

