[general]
import = ["/home/acikgozb/.config/alacritty/themes/rose-pine.toml"]

[window]
padding = {x = 10, y = 10}
decorations = "None"
opacity = 0.8

[font]
normal = { family = "IosevkaSS14", style = "Regular" }
size = 16.0
offset = { x = 0, y = 1 }

[colors.primary]
background = "#000000"

[selection]
save_to_clipboard = true

[hints]
alphabet = "F12"
enabled = []
