[general]
import = ["/home/acikgozb/.config/alacritty/themes/everforest-dark.toml"]

[window]
padding = {x = 8, y = 8}
decorations = "None"
opacity = 0.7

[font]
normal = { family = "IosevkaSS14", style = "Regular" }
size = 16.0
offset = { x = 0, y = 1 }

[selection]
save_to_clipboard = true

[hints]
alphabet = "F12"
enabled = []
