- name: Provision the VM
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Clone the dotfiles repo
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.git:
        clone: true
        repo: https://github.com/acikgozb/dotfiles.git
        dest: "~/.config"
