- name: Download dotnet-tools.
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: /tmp
    mode: "0700"

- name: Install .NET via dotnet-tools.
  ansible.builtin.shell:
    cmd: /tmp/dotnet-install.sh --channel {{ dotnet_sdk_version }}
  register: dotnet_install_out
  changed_when: not dotnet_install_out.stderr is defined

- name: Remove the temporary files.
  ansible.builtin.file:
    path: /tmp/dotnet-install.sh
    state: absent
