- name: Download dotnet-tools.
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: /tmp
    mode: "0700"

- name: Install .NET via dotnet-tools.
  ansible.builtin.shell:
    cmd: /tmp/dotnet-install.sh --channel {{ dotnet_sdk_version }}
  register: dotnet_install_out
  changed_when: not dotnet_install_out.stderr is defined

- name: Remove the temporary files.
  ansible.builtin.file:
    path: /tmp/dotnet-install.sh
    state: absent

- name: Verify that .NET is installed.
  block:
    - name: Get info about .NET version.
      ansible.builtin.shell:
        cmd: dotnet --version
      register: dotnet_version_out

    - name: Ensure that the version output exists.
      ansible.builtin.debug:
        msg: .NET is installed successfully.
      when: dotnet_version_out.stdout is defined
