- name: Install .NET via apt.
  ansible.builtin.apt:
    name: "{{ dotnet_pkg_name }}"
    state: present

- name: Verify that .NET is installed.
  block:
    - name: Get info about .NET version.
      ansible.builtin.shell:
        cmd: dotnet --version
      register: dotnet_version_out

    - name: Ensure that the version output exists.
      ansible.builtin.debug:
        msg: .NET is installed successfully.
      when: dotnet_version_out.stdout is defined
