alacritty_git_repo: https://github.com/alacritty/alacritty.git

alacritty_deps:
  Archlinux:
    - cmake
    - freetype2
    - fontconfig
    - pkg-config
    - make
    - libxcb
    - libxkbcommon
    - python
